#!/usr/bin/python

import sys
import subprocess

def main():
    cont_id = sys.argv[1]
    cmd = sys.argv[2]
    args = sys.argv[3:]

    command = "nsenter --target {} --preserve-credentials --mount --uts --pid --net --user --root --wd {}".format(cont_id, cmd)
    command_list = command.split(" ")
    command_list.extend(args)

    subprocess.call(command_list)

if __name__ == '__main__':
    main()